### ISSUE TITLE
Implement some interactive UI logic in `Apply` page

### ISSUE THREAD

**Issue by shu07002** [LIKELION-SOGANG/LIKELION-WEBSITE-NEXTJS#59]
## Description

어플라이 페이지의 인터렉션을 구현합니다.

1. 지원서 작성 버튼을 누를 시 다음 단계로 넘어가도록 합니다.
2. 진행 단계에 따라 프로그레스 바를 구현합니다.
3. 모바일 환경에서 지원시 PCOnly 모달을 띄웁니다.

## Todolist
- [x] 단계별 넘어가는 버튼
- [x] 프로그레스 바
- [x] 모바일 환경PCOnly Modal

## Etc

<br>
추가적인 사항을 작성해주세요.(선택)
<br>

**Comment by rmdnps10** [comment]
제목 컨벤션이랑 Assignees랑 labels할당 부탁드립니당! ㅎㅎ

**Comment by rmdnps10** [comment]
브랜치명도 해당 이슈 내용이 포함된 형태면 좋을 거 같습니다! `feature/apply-page-interaction#59` 이런식으로??

이슈 TODOLIST 에 어떤 인터랙션을 구현하는건지 표시해주시면 감사하겠습니다!

**Comment by shu07002** [comment]
넵! 바꾸겠습니다!
이전 이슈들도 라벨이랑 이슈 네임 수정했습니다!

**Comment by rmdnps10** [comment]
감사합니다!! ㅎㅎ

**Comment by rmdnps10** [comment]
@shu07002 제목 컨벤션맞게 수정해보았는데 이런 느낌으로 제목 작성해주시면 될 거 같아요!

**Comment by shu07002** [comment]
아하 알겠습니다! 다음 이슈부터 제대로 적용해보겠습니다!
